### ISSUE TITLE
Swapping teams for LCN and SBT?

### ISSUE THREAD

**Issue by m4v15** [InFact-coop/Organisation#3]
So Max and Rebe would be going to Edinburgh and Me and Jen would stay in London - this is the only one that needs to change but will also mean Me, Jen and Aisha do the RSBC Design day, then Jen and Rebe would switch, so Rebe and Me do the build for RSBC and Jen and Max would do the design and build for Ava.

Travel dates for Edinburgh (AFAIK) are 23:50 train on Monday night, staying Tuesday, Wednesday and travel back on Thursday night (or maybe stay Thursday and travel back Friday)

If everyone's happy with this I'm happy to change the thing on the calendar 🤙

**Comment by Jen-Harris** [comment]
Sounds good to me!
