### ISSUE TITLE
MAC-UK Presentation

### ISSUE THREAD

**Issue by rebecacalvoquintero** [InFact-coop/Organisation#5]
- [ ] The Problem

How might we visualise the key contacts for each client?
- [ ] The solution (summarised)
Create an interactive app that allows you to move between boroughs, organisations and contacts.
- [ ] The aims of the solution
To make it easier to access key information
- [ ] How it works
..
- [ ] Quick Demo
...
- [ ] How you would user test this?
* Allow therapists to user test the app on their phone to access client information.
* Allow therapists to be aware of the organisations that are present in each borough.

- [ ] What you would do to develop it further?
* Connect this with google contacts
* Dynamically create charts that represent Organisations' structure.

**Comment by astroash** [comment]
@rebecacalvoquintero can this be closed?

**Comment by rebecacalvoquintero** [comment]
yep :) ill close it ;)
